name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@main

    - name: Install build essentials
      run: sudo apt-get install build-essential -y

    - name: Build
      run: gcc -o hello hello.cpp

    - name: Run
      run: ./hello
